server:
  port: 8080
  #  servlet:
  #    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  http2:
    enabled: true
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    connection-timeout: 5s
  shutdown: graceful

spring:
  application:
    name: statisfy
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5432/statisfy
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
  #        cache:
  #          use_second_level_cache: true
  #          use_query_cache: true
  #          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      connect-timeout: 2000
      client-name: statisfy-redis
      database: 0

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

  # Session Configuration
  session:
    store-type: redis
    redis:
      namespace: statisfy:session
      flush-mode: on_save

  # Async Executor Configuration
  task:
    execution:
      pool:
        core-size: 8
        max-size: 32
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: statisfy-async-

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,caches,flyway,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      group:
        readiness:
          include: db,redis,diskSpace
        liveness:
          include: ping
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      sla:
        http.server.requests: 50ms,100ms,200ms,500ms,1s
    tags:
      application: statisfy-server
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: "F93sdf9j3r023r90wefjwef9w023rwejfw09"
  expiration: 86400000 # 24 hours

# NewsAPI configuration
news-api:
  key: "8366fc3ce12040338505bd85c80a6c2f"
  base-url: https://newsapi.org/v2
  scheduler:
    enabled: true
    cron: "0 */30 * * * *" # Every 30 minutes

# OpenAI API configuration
openai:
  api:
    key: "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"
    model: gpt-3.5-turbo
    timeout: 60 # seconds

firebase:
  enabled: ${FIREBASE_ENABLED:true}
  config-file: ${FIREBASE_CONFIG_FILE:firebase-service-account.json}

scraping:
  enabled: true
  scheduler:
    cron: "0 0 */3 * * *" # Every 3 hours
  sites:
    - name: kun.uz
      url: https://kun.uz/en/news/categories
    - name: gazeta.uz
      url: https://www.gazeta.uz/en/

# Rate Limiting Configuration
rate-limiting:
  enabled: false
  capacity: 50
  refill-tokens: 50
  refill-duration: 3600 # seconds

# Logging configuration
logging:
  level:
    root: INFO
    uz.dckroff.statisfy: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: INFO
    org.springframework.cache: INFO
    org.springframework.data.redis: INFO
  file:
    name: logs/statisfy.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Security Headers Configuration
security:
  headers:
    content-security-policy: "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'"
    strict-transport-security: "max-age=31536000; includeSubDomains"
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-xss-protection: "1; mode=block"
    referrer-policy: no-referrer 

# Настройки сбора статистики
statistics-collector:
  enabled: true
  connection-timeout: 10000
  user-agent: "Statisfy-StatisticsCollector/1.0"
  sources:
    - name: "worldbank"
      url: "http://api.worldbank.org/v2"
      category: "general"
      enabled: true
    - name: "openexchangerates"
      url: "https://openexchangerates.org/api"
      api-key: ${OPEN_EXCHANGE_RATES_API_KEY:your_key_here}
      category: "economic"
      enabled: true

# Настройки сбора фактов
fact-collector:
  enabled: true
  connection-timeout: 10000
  user-agent: "Statisfy-FactCollector/1.0"
  max-facts-per-run: 20
  openapi: 3.0.0
  sources:
    - name: "wikipedia"
      url: "https://en.wikipedia.org/api/rest_v1"
      category: "general"
      enabled: true
    - name: "numbersapi"
      url: "http://numbersapi.com"
      category: "math"
      enabled: true
    - name: "historyapi"
      url: "https://history.muffinlabs.com"
      category: "history"
      enabled: true
    - name: "spacenews"
      url: "https://api.spaceflightnewsapi.net/v3"
      category: "science"
      enabled: true 