server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  application:
    name: statisfy
  
  datasource:
    url: jdbc:postgresql://localhost:5432/statisfy
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms,100ms,200ms,500ms,1s
    tags:
      application: statisfy-server
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: "F93sdf9j3r023r90wefjwef9w023rwejfw09"
  expiration: 86400000 # 24 hours

# NewsAPI configuration
news-api:
  key: ${NEWS_API_KEY:your_news_api_key_here}
  base-url: https://newsapi.org/v2
  scheduler:
    enabled: false
    cron: "0 */30 * * * *" # Every 30 minutes

# OpenAI API configuration
openai:
  api:
    key: ${OPENAI_API_KEY:your_openai_api_key_here}
    model: gpt-3.5-turbo
    timeout: 60 # seconds

firebase:
  enabled: ${FIREBASE_ENABLED:true}
  config-file: ${FIREBASE_CONFIG_FILE:firebase-service-account.json}

scraping:
  enabled: false
  scheduler:
    cron: "0 0 */3 * * *" # Every 3 hours
  sites:
    - name: kun.uz
      url: https://kun.uz/en/news/categories
    - name: gazeta.uz
      url: https://www.gazeta.uz/en/

# Logging configuration
logging:
  level:
    root: INFO
    uz.dckroff.statisfy: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  file:
    name: logs/statisfy.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30 