server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: statisfy
  
  datasource:
    url: jdbc:postgresql://localhost:5432/statisfy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_which_should_be_at_least_32_characters_long}
  expiration: 86400000 # 24 hours

# NewsAPI configuration
news-api:
  key: ${NEWS_API_KEY:your_news_api_key_here}
  base-url: https://newsapi.org/v2
  scheduler:
    enabled: true
    cron: "0 */30 * * * *" # Every 30 minutes

# OpenAI API configuration
openai:
  api:
    key: ${OPENAI_API_KEY:your_openai_api_key_here}
    model: gpt-3.5-turbo
    timeout: 60 # seconds

scraping:
  enabled: true
  scheduler:
    cron: "0 0 */3 * * *" # Every 3 hours
  sites:
    - name: kun.uz
      url: https://kun.uz/en/news/categories
    - name: gazeta.uz
      url: https://www.gazeta.uz/en/

logging:
  level:
    uz.dckroff.statisfy: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO 